# Health Burden

## Set up

In [63]:
# Read in data
import plotly.plotly as py
import plotly.graph_objs as go
import numpy as np
import pandas
data = pandas.read_csv('./data/prepped/risk-data.csv')

## Data Structure
To get a basic sense of your dataset, check the following:

- How large is the dataset (rows, columns)?
- What are the variables present in the dataset?
- What is the data type of each variable?

In [64]:
# how large is it?
rows = data.shape[0]
cols = data.shape[1]
print('rows: ', rows)
print('cols: ', cols)

# what variables are present?
# print(list(data)) # can be seen with data types 

# what data types?
print(data.dtypes)

rows:  1950
cols:  12
country          object
country.code     object
super.region     object
region           object
sex              object
age              object
pop             float64
alcohol.use     float64
drug.use        float64
high.meat       float64
low.exercise    float64
smoking         float64
dtype: object


## Univariate Analysis
For each variable of interest, answer the following questions. As you do so, begin making a list of further questions you would like to investigate:

- What does the distribution of each (risk factor) variable look like?
- Is any variable ever missing (and if so, why)?
- What are the basic summary statistics (mean, median, standard deviation) each variable, and what is it's range (min/max)?
- What do you find surprising?

In [83]:

# basic summary statistics
data.describe()

#


alc_data = np.histogram(data['alcohol.use'])
print(hist_data)
plt.figure()
data.plot.hist()

# not showing histograms?

C:\Users\Randi\Anaconda3\lib\site-packages\numpy\lib\function_base.py:3834: RuntimeWarning:

Invalid value encountered in percentile

C:\Users\Randi\Anaconda3\lib\site-packages\matplotlib\pyplot.py:524: RuntimeWarning:

More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).

(array([  18, 1395,  274,  146,   53,   29,   20,    8,    6,    1], dtype=int64), array([-106.23200796,  -29.31739204,   47.59722389,  124.51183982,
        201.42645575,  278.34107168,  355.25568761,  432.17030354,
        509.08491947,  585.9995354 ,  662.91415133]))

## Univariate analysis (by age)
In this section, you should investigate how each (risk-variable) varies by **age group**. More specifically, consider if the distribution of each variable of interest (smoking, alcohol use, etc.) is consistent across age-groups.

In [59]:
#grouped variables by age group
#shows distributions
data.groupby('age').describe()

C:\Users\Randi\Anaconda3\lib\site-packages\numpy\lib\function_base.py:3834: RuntimeWarning:

Invalid value encountered in percentile

                   alcohol.use    drug.use   high.meat  low.exercise  \
age
15-49 years count   390.000000  390.000000  390.000000    390.000000
            mean     20.502819    5.443420    0.165258      3.367872
            std      22.899716    7.088821    0.184176      3.156864
            min       0.516131    0.244291    0.000176      0.308731
            25%       5.094456    1.227520    0.046847      1.515902
            50%      11.066746    3.398823    0.121571      2.373879
            75%      30.856604    7.235169    0.221302      4.021894
            max     159.245729   69.445756    1.672639     25.281779
5-14 years  count   390.000000  390.000000    0.000000      0.000000
            mean      0.524227    0.086837         NaN           NaN
            std       0.502376    0.219102         NaN           NaN
            min       0.002291    0.000038         NaN           NaN
            25%       0.184310    0.001315         NaN           NaN
            50%       0.371376    0.006182         NaN           NaN
            75%       0.708627    0.057566         NaN           NaN
            max       3.885040    1.560129         NaN           NaN
50-69 years count   390.000000  390.000000  390.000000    390.000000
            mean     80.085559   12.328980    2.123360     52.031415
            std      80.199394   14.766957    2.257043     39.681000
            min      -1.338063    0.287084    0.002457      7.450645
            25%      21.700210    3.149318    0.576210     26.621804
            50%      49.913334    7.535917    1.500212     40.743931
            75%     116.512639   16.813156    2.862686     63.176327
            max     495.789573  146.928034   19.282832    247.999607
70+ years   count   390.000000  390.000000  390.000000    390.000000
            mean    134.418333   17.635331    5.494057    303.258043
            std     127.605472   22.410453    5.425319    130.554398
            min    -106.232008    0.892988    0.006171     66.488079
            25%      48.055981    5.421698    1.149884    206.860830
            50%      99.676411   11.726537    4.038112    274.772535
            75%     191.060497   22.461699    8.130563    384.130835
            max     662.914151  314.625888   36.087746    844.249502
Under 5     count   390.000000  390.000000    0.000000      0.000000
            mean      0.201786    0.147215         NaN           NaN
            std       0.243022    0.363427         NaN           NaN
            min       0.001876    0.001332         NaN           NaN
            25%       0.058346    0.006889         NaN           NaN
            50%       0.115498    0.022445         NaN           NaN
            75%       0.228852    0.103460         NaN           NaN
            max       1.750790    2.516973         NaN           NaN

                            pop      smoking
age
15-49 years count  3.900000e+02   390.000000
            mean   9.757467e+06    16.867803
            std    3.789028e+07    18.247657
            min    1.178089e+04     0.532166
            25%    4.949358e+05     4.507726
            50%    2.025922e+06     9.972852
            75%    6.590636e+06    21.977467
            max    3.901690e+08   125.569280
5-14 years  count  3.900000e+02     0.000000
            mean   3.179539e+06          NaN
            std    1.114451e+07          NaN
            min    3.382364e+03          NaN
            25%    1.526850e+05          NaN
            50%    6.043500e+05          NaN
            75%    2.570008e+06          NaN
            max    1.339070e+08          NaN
50-69 years count  3.900000e+02   390.000000
            mean   3.210581e+06   211.840681
            std    1.342075e+07   206.509391
            min    3.301655e+03     6.782566
            25%    1.275715e+05    63.915359
            50%    5.251606e+05   141.771667
            75%    1.695422e+06   278.971443
            max    1.564822e+08  1340.393070
70+ years   count  3.900000e+02   390.000000
            mean   1.019981e+06   669.852828
            std    3.699646e+06   553.213210
            min    3.563755e+02    18.266753
            25%    3.110225e+04   232.680596
            50%    1.517975e+05   520.704919
            75%    5.557195e+05   929.379300
            max    4.285894e+07  2691.239677
Under 5     count  3.900000e+02     0.000000
            mean   1.720972e+06          NaN
            std    5.676589e+06          NaN
            min    1.866654e+03          NaN
            25%    8.701891e+04          NaN
            50%    3.487635e+05          NaN
            75%    1.460014e+06          NaN
            max    6.534111e+07          NaN

## Univariate analysis (by sex)
In this section, you should investigate how each (risk-variable) varies by **sex group**. More specifically, consider if the distribution of each variable of interest (smoking, alcohol use, etc.) is consistent across sex-groups. Depending on your procedure, you may need to **reshape your data**.

In [61]:
data.groupby('sex').describe()

C:\Users\Randi\Anaconda3\lib\site-packages\numpy\lib\function_base.py:3834: RuntimeWarning:

Invalid value encountered in percentile

              alcohol.use    drug.use   high.meat  low.exercise           pop  \
sex
female count   975.000000  975.000000  585.000000    585.000000  9.750000e+02
       mean     25.959477    2.746114    2.174843    110.555531  3.746894e+06
       std      59.899385    4.570012    3.446836    148.043429  1.850862e+07
       min    -106.232008    0.000038    0.000176      0.308731  4.712220e+02
       25%       0.212307    0.030215         NaN           NaN  1.034577e+05
       50%       3.997471    1.156871         NaN           NaN  5.218150e+05
       75%      26.948108    3.981538         NaN           NaN  2.127735e+06
       max     662.914151   72.356721   30.586665    844.249502  3.651006e+08
male   count   975.000000  975.000000  585.000000    585.000000  9.750000e+02
       mean     68.333613   11.510600    3.013608    128.549356  3.808522e+06
       std     101.568208   18.547786    4.526852    157.879519  1.974887e+07
       min     -57.962287    0.000106    0.000517      0.805267  3.563755e+02
       25%       0.379552    0.028427         NaN           NaN  9.674848e+04
       50%      22.704687    5.733104         NaN           NaN  4.951956e+05
       75%     102.259073   17.213273         NaN           NaN  2.057315e+06
       max     577.704003  314.625888   36.087746    752.703100  3.901690e+08

                  smoking
sex
female count   585.000000
       mean    139.340281
       std     210.572682
       min       0.532166
       25%            NaN
       50%            NaN
       75%            NaN
       max    1716.575958
male   count   585.000000
       mean    459.700594
       std     535.549651
       min       3.416982
       25%            NaN
       50%            NaN
       75%            NaN
       max    2691.239677

## Univariate analysis (by country)
In this section, you should investigate how each (risk-variable) varies by **country**. Given the number of countries present in the dataset, I suggest that you aggregate your data by region. In order to do this, you'll need to **convert death rates to deaths** using the `pop` column.

In [62]:
data.groupby('country').describe()

C:\Users\Randi\Anaconda3\lib\site-packages\numpy\lib\function_base.py:3834: RuntimeWarning:

Invalid value encountered in percentile

                            alcohol.use   drug.use  high.meat  low.exercise  \
country
Afghanistan          count    10.000000  10.000000   6.000000      6.000000
                     mean     44.291492   3.953610   2.220876    344.475095
                     std      63.030578   4.797732   1.739002    353.015416
                     min       0.055433   0.005093   0.124977     14.654225
                     25%       0.216565   0.049915        NaN           NaN
                     50%      11.295182   1.946429        NaN           NaN
                     75%      67.708678   6.538323        NaN           NaN
                     max     188.709726  13.426431   4.224769    844.249502
Albania              count    10.000000  10.000000   6.000000      6.000000
                     mean     31.368240   5.777630   0.528425     70.669538
                     std      52.242660   9.719647   0.505786     89.625233
                     min       0.043967   0.000150   0.037688      1.443261
                     25%       0.237097   0.002171        NaN           NaN
                     50%       8.650945   1.449109        NaN           NaN
                     75%      45.664576   4.484826        NaN           NaN
                     max     165.076181  28.759427   1.370637    196.035253
Algeria              count    10.000000  10.000000   6.000000      6.000000
                     mean     12.968856   3.175085   0.308917    135.067102
                     std      19.331411   4.878769   0.259696    166.449187
                     min       0.090092   0.002071   0.024181      3.108744
                     25%       0.161984   0.013625        NaN           NaN
                     50%       3.426438   1.127370        NaN           NaN
                     75%      13.338186   4.120773        NaN           NaN
                     max      49.127854  15.066435   0.669984    364.729855
American Samoa       count    10.000000  10.000000   6.000000      6.000000
                     mean     17.607979   2.452943   5.860601    168.852191
                     std      25.518223   3.509502   5.171044    185.597669
                     min       0.032359   0.001273   0.511018      7.356607
                     25%       0.100011   0.004238        NaN           NaN
                     50%       5.961883   1.083858        NaN           NaN
...                                 ...        ...        ...           ...
Virgin Islands, U.S. std      78.976511   9.804087   3.651164    200.832946
                     min       0.138997   0.002335   0.187547      4.517206
                     25%       0.500902   0.009274        NaN           NaN
                     50%      23.186948   1.618215        NaN           NaN
                     75%      79.932455   8.657236        NaN           NaN
                     max     228.155591  28.001869   9.528474    427.071610
Yemen                count    10.000000  10.000000   6.000000      6.000000
                     mean     24.184550   2.363609   0.243810    216.617755
                     std      36.396496   3.510949   0.194830    235.783026
                     min       0.068332   0.000940   0.014489      6.513648
                     25%       0.157612   0.005573        NaN           NaN
                     50%       4.630897   0.917759        NaN           NaN
                     75%      29.013518   2.740921        NaN           NaN
                     max     104.682345  10.846145   0.452830    534.747215
Zambia               count    10.000000  10.000000   6.000000      6.000000
                     mean    111.120301   6.902643   1.410464    108.785133
                     std     150.313165   8.484774   1.321731    123.374667
                     min       0.276511   0.687164   0.046772      1.754041
                     25%       0.630609   1.127317        NaN           NaN
                     50%      35.039879   3.994621        NaN           NaN
                     75%     199.080996   6.773765        NaN           NaN
                     max     407.552300  23.947812   3.522886    296.986592
Zimbabwe             count    10.000000  10.000000   6.000000      6.000000
                     mean     88.260948   8.004046   1.848225     85.283674
                     std     136.378998   7.602188   1.629889    101.386966
                     min       0.488036   0.792020   0.057988      0.829211
                     25%       1.104905   0.925085        NaN           NaN
                     50%      24.176691   7.138818        NaN           NaN
                     75%     111.192484  11.772815        NaN           NaN
                     max     403.270358  21.623388   4.216021    228.021108

                                     pop      smoking
country
Afghanistan          count  1.000000e+01     6.000000
                     mean   3.260755e+06   556.239888
                     std    2.837236e+06   498.431061
                     min    1.977670e+05    45.070547
                     25%    1.166672e+06          NaN
                     50%    2.515621e+06          NaN
                     75%    4.747918e+06          NaN
                     max    8.049121e+06  1373.436674
Albania              count  1.000000e+01     6.000000
                     mean   2.896299e+05   349.131893
                     std    2.456504e+05   543.404917
                     min    8.916652e+04     3.367045
                     25%    1.156330e+05          NaN
                     50%    1.758630e+05          NaN
                     75%    3.372605e+05          NaN
                     max    7.318120e+05  1418.469567
Algeria              count  1.000000e+01     6.000000
                     mean   3.963465e+06   112.475765
                     std    3.697074e+06   160.881500
                     min    7.283850e+05     2.010116
                     25%    2.253271e+06          NaN
                     50%    2.622792e+06          NaN
                     75%    3.391344e+06          NaN
                     max    1.083325e+07   421.358505
American Samoa       count  1.000000e+01     6.000000
                     mean   8.291491e+03   373.413805
                     std    6.930903e+03   431.787349
                     min    4.438835e+02    22.124837
                     25%    4.120665e+03          NaN
                     50%    5.784711e+03          NaN
...                                  ...          ...
Virgin Islands, U.S. std    7.094228e+03   215.919852
                     min    3.647128e+03     4.735092
                     25%    5.523750e+03          NaN
                     50%    7.234500e+03          NaN
                     75%    1.498100e+04          NaN
                     max    2.299700e+04   563.024031
Yemen                count  1.000000e+01     6.000000
                     mean   2.691167e+06   333.078170
                     std    2.417855e+06   333.382668
                     min    1.886350e+05    16.156015
                     25%    1.038118e+06          NaN
                     50%    2.002017e+06          NaN
                     75%    3.474412e+06          NaN
                     max    6.847943e+06   912.288204
Zambia               count  1.000000e+01     6.000000
                     mean   1.624899e+06   375.611741
                     std    1.373898e+06   455.220067
                     min    1.245770e+05     2.516403
                     25%    4.699118e+05          NaN
                     50%    1.444013e+06          NaN
                     75%    2.303127e+06          NaN
                     max    3.769950e+06  1204.889454
Zimbabwe             count  1.000000e+01     6.000000
                     mean   1.557415e+06   507.000926
                     std    1.418963e+06   671.349930
                     min    1.370630e+05     1.092613
                     25%    4.587140e+05          NaN
                     50%    1.238042e+06          NaN
                     75%    1.994282e+06          NaN
                     max    4.001236e+06  1763.709448

[1560 rows x 6 columns]

## Bivariate analysis
In this section, you should compare risks-variables to one another to see how they co-vary. Use simple statistical tests (i.e., **correlation**) and visualization as you see fit.

In [6]:
# Code goes here